/**
* katran API generated from katran.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* GeneralStatsBase.h
*
*
*/

#pragma once

#include "../serializer/GeneralStatsJsonObject.h"
#include "../serializer/GeneralStatsGetVipStatsOutputJsonObject.h"
#include "../serializer/GeneralStatsGetVipStatsInputJsonObject.h"
#include "../serializer/GeneralStatsGetLruStatsOutputJsonObject.h"

#include "../serializer/GeneralStatsGetLruMissStatsOutputJsonObject.h"

#include "../serializer/GeneralStatsGetLruFallbackStatsOutputJsonObject.h"

#include "../serializer/GeneralStatsGetIcmpTooBigStatsOutputJsonObject.h"







#include <spdlog/spdlog.h>

using namespace polycube::service::model;

class Katran;

class GeneralStatsBase {
 public:
  
  GeneralStatsBase(Katran &parent);
  
  virtual ~GeneralStatsBase();
  virtual void update(const GeneralStatsJsonObject &conf);
  virtual GeneralStatsJsonObject toJsonObject();

  /// <summary>
  /// V1 Stats
  /// </summary>
  virtual uint64_t getV1() = 0;

  /// <summary>
  /// V2 Stats
  /// </summary>
  virtual uint64_t getV2() = 0;
  virtual GeneralStatsGetVipStatsOutputJsonObject getVipStats(GeneralStatsGetVipStatsInputJsonObject input) = 0;
  virtual GeneralStatsGetLruStatsOutputJsonObject getLruStats() = 0;
  virtual GeneralStatsGetLruMissStatsOutputJsonObject getLruMissStats() = 0;
  virtual GeneralStatsGetLruFallbackStatsOutputJsonObject getLruFallbackStats() = 0;
  virtual GeneralStatsGetIcmpTooBigStatsOutputJsonObject getIcmpTooBigStats() = 0;

  std::shared_ptr<spdlog::logger> logger();
 protected:
  Katran &parent_;
};
