/**
* katran API generated from katran.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "GeneralStatsBase.h"
#include "../Katran.h"


GeneralStatsBase::GeneralStatsBase(Katran &parent)
    : parent_(parent) {}

GeneralStatsBase::~GeneralStatsBase() {}

void GeneralStatsBase::update(const GeneralStatsJsonObject &conf) {

}

GeneralStatsJsonObject GeneralStatsBase::toJsonObject() {
  GeneralStatsJsonObject conf;

  conf.setV1(getV1());
  conf.setV2(getV2());

  return conf;
}

std::shared_ptr<spdlog::logger> GeneralStatsBase::logger() {
  return parent_.logger();
}

