/**
* katran API generated from katran.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* VipRealBase.h
*
*
*/

#pragma once

#include "../serializer/VipRealJsonObject.h"






#include <spdlog/spdlog.h>

using namespace polycube::service::model;

class Vip;

class VipRealBase {
 public:
  
  VipRealBase(Vip &parent);
  
  virtual ~VipRealBase();
  virtual void update(const VipRealJsonObject &conf);
  virtual VipRealJsonObject toJsonObject();

  /// <summary>
  /// IP address of the backend server of the pool
  /// </summary>
  virtual std::string getIp() = 0;

  /// <summary>
  /// Weight of the backend in the pool
  /// </summary>
  virtual uint16_t getWeight() = 0;
  virtual void setWeight(const uint16_t &value) = 0;

  /// <summary>
  /// Flags used in the Reals
  /// </summary>
  virtual uint32_t getFlags() = 0;
  virtual void setFlags(const uint32_t &value) = 0;

  std::shared_ptr<spdlog::logger> logger();
 protected:
  Vip &parent_;
};
