/**
* katran API generated from katran.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "VipReal.h"
#include "Katran.h"


VipReal::VipReal(Vip &parent, const VipRealJsonObject &conf)
    : VipRealBase(parent) {
  address_ = conf.getIp();
  weight_ = conf.getWeight();
  flags_ = conf.getFlags();
}

VipReal::~VipReal() {}

std::string VipReal::getIp() {
  return address_;
}

uint16_t VipReal::getWeight() {
  return weight_;
}

void VipReal::setWeight(const uint16_t &value) {
  throw std::runtime_error("VipReal::setWeight: Method not implemented");
}

uint32_t VipReal::getFlags() {
  return flags_;
}

void VipReal::setFlags(const uint32_t &value) {
  throw std::runtime_error("VipReal::setFlags: Method not implemented");
}


