/**
* katran API generated from katran.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#pragma once


#include "../base/VipRealBase.h"


class Vip;

using namespace polycube::service::model;

class VipReal : public VipRealBase {
 public:
  VipReal(Vip &parent, const VipRealJsonObject &conf);
  virtual ~VipReal();

  /// <summary>
  /// IP address of the backend server of the pool
  /// </summary>
  std::string getIp() override;

  /// <summary>
  /// Weight of the backend in the pool
  /// </summary>
  uint16_t getWeight() override;
  void setWeight(const uint16_t &value) override;

  /// <summary>
  /// Flags used in the Reals
  /// </summary>
  uint32_t getFlags() override;
  void setFlags(const uint32_t &value) override;

  private:
  std::string address_;
  uint16_t weight_;
  uint32_t flags_;
};
