/**
* bmc API generated from bmc.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

#include "api/BmcApiImpl.h"
#include "../datamodel/bmc.h" // generated from datamodel

#define SERVICE_PYANG_GIT ""
#define SERVICE_SWAGGER_CODEGEN_GIT "seb-dev/b82c489"

#include <polycube/services/shared_library.h>

extern "C" const char *data_model() {
  return bmc_datamodel.c_str();
}
