/**
* katran API generated from katran.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* KatranApi.h
*
*/

#pragma once

#define POLYCUBE_SERVICE_NAME "katran"


#include "polycube/services/response.h"
#include "polycube/services/shared_lib_elements.h"

#include "GeneralStatsJsonObject.h"
#include "GeneralStatsGetIcmpTooBigStatsOutputJsonObject.h"
#include "GeneralStatsGetLruFallbackStatsOutputJsonObject.h"
#include "GeneralStatsGetLruMissStatsOutputJsonObject.h"
#include "GeneralStatsGetLruStatsOutputJsonObject.h"
#include "GeneralStatsGetVipStatsInputJsonObject.h"
#include "GeneralStatsGetVipStatsOutputJsonObject.h"
#include "KatranJsonObject.h"
#include "PortsJsonObject.h"
#include "VipJsonObject.h"
#include "VipRealJsonObject.h"
#include <vector>


#ifdef __cplusplus
extern "C" {
#endif

Response create_katran_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response create_katran_general_stats_get_icmp_too_big_stats_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response create_katran_general_stats_get_lru_fallback_stats_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response create_katran_general_stats_get_lru_miss_stats_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response create_katran_general_stats_get_lru_stats_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response create_katran_general_stats_get_vip_stats_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response create_katran_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response create_katran_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response create_katran_vip_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response create_katran_vip_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response create_katran_vip_real_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response create_katran_vip_real_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response delete_katran_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response delete_katran_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response delete_katran_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response delete_katran_vip_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response delete_katran_vip_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response delete_katran_vip_real_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response delete_katran_vip_real_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_ch_ring_size_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_default_mac_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_dyn_opt_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_enable_hc_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_forwarding_cores_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_general_stats_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_general_stats_v1_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_general_stats_v2_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_lru_size_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_max_reals_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_max_vips_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_numa_nodes_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_vip_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_vip_flags_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_vip_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_vip_real_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_vip_real_flags_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_vip_real_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_katran_vip_real_weight_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response replace_katran_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response replace_katran_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response replace_katran_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response replace_katran_vip_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response replace_katran_vip_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response replace_katran_vip_real_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response replace_katran_vip_real_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_ch_ring_size_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_default_mac_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_enable_hc_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_forwarding_cores_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_lru_size_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_max_reals_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_max_vips_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_numa_nodes_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_vip_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_vip_flags_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_vip_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_vip_real_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_vip_real_flags_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_vip_real_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_katran_vip_real_weight_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);

Response katran_list_by_id_help(const char *name, const Key *keys, size_t num_keys);
Response katran_ports_list_by_id_help(const char *name, const Key *keys, size_t num_keys);
Response katran_vip_list_by_id_help(const char *name, const Key *keys, size_t num_keys);
Response katran_vip_real_list_by_id_help(const char *name, const Key *keys, size_t num_keys);


#ifdef __cplusplus
}
#endif

