/**
* bmc API generated from bmc.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* BmcStatsGetPktCountOutputJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"


namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  BmcStatsGetPktCountOutputJsonObject : public JsonObjectBase {
public:
  BmcStatsGetPktCountOutputJsonObject();
  BmcStatsGetPktCountOutputJsonObject(const nlohmann::json &json);
  ~BmcStatsGetPktCountOutputJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// Return average pps
  /// </summary>
  uint64_t getAverage() const;
  void setAverage(uint64_t value);
  bool averageIsSet() const;
  void unsetAverage();

private:
  uint64_t m_average;
  bool m_averageIsSet;
};

}
}
}

