/**
* bmc API generated from bmc.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* BmcStatsGetPktCountInputJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"


namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  BmcStatsGetPktCountInputJsonObject : public JsonObjectBase {
public:
  BmcStatsGetPktCountInputJsonObject();
  BmcStatsGetPktCountInputJsonObject(const nlohmann::json &json);
  ~BmcStatsGetPktCountInputJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// How long it should read the measurement
  /// </summary>
  uint32_t getTime() const;
  void setTime(uint32_t value);
  bool timeIsSet() const;
  void unsetTime();

private:
  uint32_t m_time;
  bool m_timeIsSet;
};

}
}
}

