/**
* bmc API generated from bmc.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* BmcStatsResetAllOutputJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"


namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  BmcStatsResetAllOutputJsonObject : public JsonObjectBase {
public:
  BmcStatsResetAllOutputJsonObject();
  BmcStatsResetAllOutputJsonObject(const nlohmann::json &json);
  ~BmcStatsResetAllOutputJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// Return TRUE is the stats were correctly reset
  /// </summary>
  bool getResult() const;
  void setResult(bool value);
  bool resultIsSet() const;
  void unsetResult();

private:
  bool m_result;
  bool m_resultIsSet;
};

}
}
}

