/**
* iptables API generated from iptables.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* ChainStatsBase.h
*
*
*/

#pragma once

#include "../serializer/ChainStatsJsonObject.h"






#include <spdlog/spdlog.h>

using namespace polycube::service::model;

class Chain;

class ChainStatsBase {
 public:
  
  ChainStatsBase(Chain &parent);
  
  virtual ~ChainStatsBase();
  virtual void update(const ChainStatsJsonObject &conf);
  virtual ChainStatsJsonObject toJsonObject();

  /// <summary>
  /// Rule Identifier
  /// </summary>
  virtual uint32_t getId() = 0;

  /// <summary>
  /// Number of packets matching the rule
  /// </summary>
  virtual uint64_t getPkts() = 0;

  /// <summary>
  /// Number of bytes matching the rule
  /// </summary>
  virtual uint64_t getBytes() = 0;

  /// <summary>
  /// Description
  /// </summary>
  virtual std::string getDescription() = 0;

  std::shared_ptr<spdlog::logger> logger();
 protected:
  Chain &parent_;
};
