/**
* iptables API generated from iptables.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "ChainStatsBase.h"
#include "../Iptables.h"


ChainStatsBase::ChainStatsBase(Chain &parent)
    : parent_(parent) {}

ChainStatsBase::~ChainStatsBase() {}

void ChainStatsBase::update(const ChainStatsJsonObject &conf) {

}

ChainStatsJsonObject ChainStatsBase::toJsonObject() {
  ChainStatsJsonObject conf;

  conf.setId(getId());
  conf.setPkts(getPkts());
  conf.setBytes(getBytes());
  conf.setDescription(getDescription());

  return conf;
}

std::shared_ptr<spdlog::logger> ChainStatsBase::logger() {
  return parent_.logger();
}

