/**
* iptables API generated from iptables.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "SessionTableBase.h"
#include "../Iptables.h"


SessionTableBase::SessionTableBase(Iptables &parent)
    : parent_(parent) {}

SessionTableBase::~SessionTableBase() {}

void SessionTableBase::update(const SessionTableJsonObject &conf) {

}

SessionTableJsonObject SessionTableBase::toJsonObject() {
  SessionTableJsonObject conf;

  conf.setSrc(getSrc());
  conf.setDst(getDst());
  conf.setL4proto(getL4proto());
  conf.setSport(getSport());
  conf.setDport(getDport());
  conf.setState(getState());

  return conf;
}

std::shared_ptr<spdlog::logger> SessionTableBase::logger() {
  return parent_.logger();
}

