/**
* bmc API generated from bmc.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "BmcStatsBase.h"
#include "../Bmc.h"


BmcStatsBase::BmcStatsBase(Bmc &parent)
    : parent_(parent) {}

BmcStatsBase::~BmcStatsBase() {}

void BmcStatsBase::update(const BmcStatsJsonObject &conf) {

}

BmcStatsJsonObject BmcStatsBase::toJsonObject() {
  BmcStatsJsonObject conf;

  conf.setGetRecvCount(getGetRecvCount());
  conf.setSetRecvCount(getSetRecvCount());
  conf.setGetRespCount(getGetRespCount());
  conf.setHitMisprediction(getHitMisprediction());
  conf.setHitCount(getHitCount());
  conf.setMissCount(getMissCount());
  conf.setUpdateCount(getUpdateCount());
  conf.setInvalidationCount(getInvalidationCount());

  return conf;
}

std::shared_ptr<spdlog::logger> BmcStatsBase::logger() {
  return parent_.logger();
}

