/**
* bmc API generated from bmc.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "MemcachedBase.h"
#include "../Bmc.h"


MemcachedBase::MemcachedBase(Bmc &parent)
    : parent_(parent) {}

MemcachedBase::~MemcachedBase() {}

void MemcachedBase::update(const MemcachedJsonObject &conf) {

  if (conf.lenIsSet()) {
    setLen(conf.getLen());
  }
  if (conf.validIsSet()) {
    setValid(conf.getValid());
  }
  if (conf.hashIsSet()) {
    setHash(conf.getHash());
  }
  if (conf.dataIsSet()) {
    setData(conf.getData());
  }
}

MemcachedJsonObject MemcachedBase::toJsonObject() {
  MemcachedJsonObject conf;

  conf.setHashKey(getHashKey());
  conf.setLen(getLen());
  conf.setValid(getValid());
  conf.setHash(getHash());
  conf.setData(getData());

  return conf;
}

std::shared_ptr<spdlog::logger> MemcachedBase::logger() {
  return parent_.logger();
}

