/**
* lbrp API generated from lbrp.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

#include "api/LbrpApiImpl.h"
#include "../datamodel/lbrp.h" // generated from datamodel

#define SERVICE_PYANG_GIT ""
#define SERVICE_SWAGGER_CODEGEN_GIT "seb-dev/9ed7767"

#include <polycube/services/shared_library.h>

extern "C" const char *data_model() {
  return lbrp_datamodel.c_str();
}
