/**
* lbrp API generated from lbrp.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "Ports.h"
#include "Lbrp.h"


Ports::Ports(polycube::service::Cube<Ports> &parent,
    std::shared_ptr<polycube::service::PortIface> port,
    const PortsJsonObject &conf)
    : PortsBase(parent, port) {
    setType(conf.getType());
  if (conf.ipIsSet()) {
    setIp(conf.getIp());
  }

}

Ports::~Ports() {}

PortsTypeEnum Ports::getType() {
  throw std::runtime_error("Ports::getType: Method not implemented");
}

void Ports::setType(const PortsTypeEnum &value) {
  throw std::runtime_error("Ports::setType: Method not implemented");
}

std::string Ports::getIp() {
  throw std::runtime_error("Ports::getIp: Method not implemented");
}

void Ports::setIp(const std::string &value) {
  throw std::runtime_error("Ports::setIp: Method not implemented");
}


