/**
* katran API generated from katran.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "VipRealJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

VipRealJsonObject::VipRealJsonObject() {
  m_ipIsSet = false;
  m_weightIsSet = false;
  m_flagsIsSet = false;
}

VipRealJsonObject::VipRealJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_ipIsSet = false;
  m_weightIsSet = false;
  m_flagsIsSet = false;


  if (val.count("ip")) {
    setIp(val.at("ip").get<std::string>());
  }

  if (val.count("weight")) {
    setWeight(val.at("weight").get<uint16_t>());
  }

  if (val.count("flags")) {
    setFlags(val.at("flags").get<uint32_t>());
  }
}

nlohmann::json VipRealJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_ipIsSet) {
    val["ip"] = m_ip;
  }

  if (m_weightIsSet) {
    val["weight"] = m_weight;
  }

  if (m_flagsIsSet) {
    val["flags"] = m_flags;
  }

  return val;
}

std::string VipRealJsonObject::getIp() const {
  return m_ip;
}

void VipRealJsonObject::setIp(std::string value) {
  m_ip = value;
  m_ipIsSet = true;
}

bool VipRealJsonObject::ipIsSet() const {
  return m_ipIsSet;
}



uint16_t VipRealJsonObject::getWeight() const {
  return m_weight;
}

void VipRealJsonObject::setWeight(uint16_t value) {
  m_weight = value;
  m_weightIsSet = true;
}

bool VipRealJsonObject::weightIsSet() const {
  return m_weightIsSet;
}

void VipRealJsonObject::unsetWeight() {
  m_weightIsSet = false;
}

uint32_t VipRealJsonObject::getFlags() const {
  return m_flags;
}

void VipRealJsonObject::setFlags(uint32_t value) {
  m_flags = value;
  m_flagsIsSet = true;
}

bool VipRealJsonObject::flagsIsSet() const {
  return m_flagsIsSet;
}

void VipRealJsonObject::unsetFlags() {
  m_flagsIsSet = false;
}


}
}
}

